### ISSUE TITLE
Publish updated maven artifact

### ISSUE THREAD

**Issue by wsharlan** [MinesJTK/jtk#9]
Would we now be able to publish an updated maven artifact to https://mvnrepository.com/artifact/edu.mines.jtk/edu-mines-jtk ?   Maybe version 1.1.0?  Or 1.0.1?

Were we waiting on some sonatype credentials?

Do we still want to use the same groupId and artifactId?

Here is the original issue from the previous project: https://github.com/dhale/jtk/issues/29

**Comment by chrisengelsma** [comment]
I don't have any sonatype credentials right now, I believe since @dhale registered the original edu.mines.jtk domain space there then he'd have to add users or something along those lines. 

My vote goes for 1.1.0 as the 1.0.0 is pretty old, and there have been enhancements since then

**Comment by chrisengelsma** [comment]
I've set up a Sonatype account and requested to be added to the groupID for the JTK, however... They have changed their policy to where you must own the domain that reflects the groupID in order to publish.

This means that we need to own mines.edu in order to publish with an artifact "edu.mines....".  I'm not sure if this means publishing on the nexus is out for us or not.

I will ask @dhale if there's some permissions he could access on his end to add me as a contributor.

**Comment by chrisengelsma** [comment]
Dave was able to get me permission to contribute onto the Nexus, so I can go ahead and publish the next artifact. Were we thinking 1.1.0 ?

**Comment by wsharlan** [comment]
Great.  Yes, 1.1.0 seems like a good choice.

**Comment by dhale** [comment]
Yep. Semantic versioning

**Comment by chrisengelsma** [comment]
I've published the artifact to the nexus, it should take a while to index in, but I will check it periodically to make sure I didn't screw something up.  Also, you can find the latest release in the GH releases section here: https://github.com/MinesJTK/jtk/releases
